USE [master]
GO

/****** Object:  Database [RadarStatusPowerData]    Script Date: 2015/3/31 17:48:56 ******/
CREATE DATABASE [RadarStatusPowerData]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RadarStatusPowerData', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\RadarStatusPowerData.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'RadarStatusPowerData_log', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\RadarStatusPowerData_log.ldf' , SIZE = 2048KB , MAXSIZE = 102400KB , FILEGROWTH = 10%)
GO

ALTER DATABASE [RadarStatusPowerData] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RadarStatusPowerData].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RadarStatusPowerData] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RadarStatusPowerData] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RadarStatusPowerData] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RadarStatusPowerData] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RadarStatusPowerData] SET ARITHABORT OFF 
GO

ALTER DATABASE [RadarStatusPowerData] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [RadarStatusPowerData] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RadarStatusPowerData] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RadarStatusPowerData] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RadarStatusPowerData] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RadarStatusPowerData] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RadarStatusPowerData] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RadarStatusPowerData] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RadarStatusPowerData] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RadarStatusPowerData] SET  DISABLE_BROKER 
GO

ALTER DATABASE [RadarStatusPowerData] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RadarStatusPowerData] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RadarStatusPowerData] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RadarStatusPowerData] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RadarStatusPowerData] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RadarStatusPowerData] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RadarStatusPowerData] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RadarStatusPowerData] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [RadarStatusPowerData] SET  MULTI_USER 
GO

ALTER DATABASE [RadarStatusPowerData] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RadarStatusPowerData] SET DB_CHAINING OFF 
GO

ALTER DATABASE [RadarStatusPowerData] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [RadarStatusPowerData] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [RadarStatusPowerData] SET  READ_WRITE 
GO

ALTER DATABASE [RadarStatusPowerData] SET DELAYED_DURABILITY = DISABLED 
GO


