#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseOperate
{
	using System;
	using System.ComponentModel;
	using System.Data.Linq.Mapping;


	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="RadarStatusPowerData")]
	public partial class RadarDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
	#region 可扩展性方法定义
	partial void OnCreated();
	partial void InsertAlarmStatusTable(AlarmStatusTable instance);
	partial void UpdateAlarmStatusTable(AlarmStatusTable instance);
	partial void DeleteAlarmStatusTable(AlarmStatusTable instance);
	partial void InsertControlStatusTable(ControlStatusTable instance);
	partial void UpdateControlStatusTable(ControlStatusTable instance);
	partial void DeleteControlStatusTable(ControlStatusTable instance);
	partial void InsertPowerDataTable(PowerDataTable instance);
	partial void UpdatePowerDataTable(PowerDataTable instance);
	partial void DeletePowerDataTable(PowerDataTable instance);
	partial void InsertStationParaTable(StationParaTable instance);
	partial void UpdateStationParaTable(StationParaTable instance);
	partial void DeleteStationParaTable(StationParaTable instance);
	#endregion
		
		public RadarDataClassesDataContext() : 
				base(global::DataBaseOperate.Properties.Settings.Default.RadarStatusPowerDataConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public RadarDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RadarDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RadarDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RadarDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AlarmStatusTable> AlarmStatusTable
		{
			get
			{
				return this.GetTable<AlarmStatusTable>();
			}
		}
		
		public System.Data.Linq.Table<ControlStatusTable> ControlStatusTable
		{
			get
			{
				return this.GetTable<ControlStatusTable>();
			}
		}
		
		public System.Data.Linq.Table<PowerDataTable> PowerDataTable
		{
			get
			{
				return this.GetTable<PowerDataTable>();
			}
		}
		
		public System.Data.Linq.Table<StationParaTable> StationParaTable
		{
			get
			{
				return this.GetTable<StationParaTable>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AlarmStatusTable")]
	public partial class AlarmStatusTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID;
		
		private string _StationID;
		
		private System.DateTime _DateTime;
		
		private System.Nullable<bool> _PowerGridUnderVolOnce;
		
		private System.Nullable<bool> _PowerGridUnderVolQuintic;
		
		private System.Nullable<bool> _LowPowerFailureOnce;
		
		private System.Nullable<bool> _LowPowerFailureQuintic;
		
		private System.Nullable<bool> _FilaVolFailureOnce;
		
		private System.Nullable<bool> _FilaVolFailureQuintic;
		
		private System.Nullable<bool> _TitPumpFailureOnce;
		
		private System.Nullable<bool> _TitPumpFailureQuintic;
		
		private System.Nullable<bool> _FocusCoilVolFailureOnce;
		
		private System.Nullable<bool> _FocusCoilVolFailureQuintic;
		
		private System.Nullable<bool> _TransmitOverVolOnce;
		
		private System.Nullable<bool> _TransmitOverVolQuintic;
		
		private System.Nullable<bool> _TransmitOverCurOnce;
		
		private System.Nullable<bool> _TransmitOverCurQuintic;
		
		private System.Nullable<bool> _FocusCoilCurFailureOnce;
		
		private System.Nullable<bool> _FocusCoilCurFailureQuintic;
		
		private System.Nullable<bool> _FocusCoilAirFlowFailureOnce;
		
		private System.Nullable<bool> _FocusCoilAirFlowFailureQuintic;
		
		private System.Nullable<bool> _TriggerFailureOnce;
		
		private System.Nullable<bool> _TriggerFailureQuintic;
		
		private System.Nullable<bool> _ChargingFeedbackFlowRectifierUnderVolOnce;
		
		private System.Nullable<bool> _ChargingFeedbackFlowRectifierUnderVolQuintic;
		
		private System.Nullable<bool> _ChargingFailureOnce;
		
		private System.Nullable<bool> _ChargingFailureQuintic;
		
		private System.Nullable<bool> _ModulatorOverOnce;
		
		private System.Nullable<bool> _ModulatorOverQuintic;
		
		private System.Nullable<bool> _ModulatorNegPeakOverOnce;
		
		private System.Nullable<bool> _ModulatorNegPeakOverQuintic;
		
		private System.Nullable<bool> _ModulatorSwitchFailureOnce;
		
		private System.Nullable<bool> _ModulatorSwitchFailureQuintic;
		
		private System.Nullable<bool> _KlystronOverCurOnce;
		
		private System.Nullable<bool> _KlystronOverCurQuintic;
		
		private System.Nullable<bool> _KlystronFilaFailureOnce;
		
		private System.Nullable<bool> _KlystronFilaFailureQuintic;
		
		private System.Nullable<bool> _KlystronTitPumpFailureOnce;
		
		private System.Nullable<bool> _KlystronTitPumpFailureQuintic;
		
		private System.Nullable<bool> _KlystronAirTempAlarmOnce;
		
		private System.Nullable<bool> _KlystronAirTempAlarmQuintic;
		
		private System.Nullable<bool> _KlystronAirFlowAlarmOnce;
		
		private System.Nullable<bool> _KlystronAirFlowAlarmQuintic;
		
		private System.Nullable<bool> _WaveGuidPressAlarmOnce;
		
		private System.Nullable<bool> _WaveGuidPressAlarmQuintic;
		
		private System.Nullable<bool> _WaveGuidArcAlarmOnce;
		
		private System.Nullable<bool> _WaveGuidArcAlarmQuintic;
		
		private System.Nullable<bool> _TankLevelAlarmOnce;
		
		private System.Nullable<bool> _TankLevelAlarmQuintic;
		
		private System.Nullable<bool> _TankTempAlarmOnce;
		
		private System.Nullable<bool> _TankTempAlarmQuintic;
		
		private System.Nullable<bool> _AntennaWaveGuidChain;
		
		private System.Nullable<bool> _AntennaCirculatorOverHeat;
		
		private System.Nullable<bool> _RackDoorChainOnce;
		
		private System.Nullable<bool> _RackDoorChainQuintic;
		
		private System.Nullable<bool> _RackAirTempAlarmOnce;
		
		private System.Nullable<bool> _RackAirTempAlarmQuintic;
		
		private System.Nullable<bool> _RackAirFlowAlarmOnce;
		
		private System.Nullable<bool> _RackAirFlowAlarmQuintic;
		
		private System.Nullable<bool> _DutyCycleOverOnce;
		
		private System.Nullable<bool> _DutyCycleOverQuintic;
		
		private System.Nullable<bool> _WaveGuidPressHumidityReq;
		
		private System.Nullable<bool> _ModulatorSwitchReq;
		
		private System.Nullable<bool> _AfterChargingFair;
		
		private System.Nullable<bool> @__510VFailureOnce;
		
		private System.Nullable<bool> @__510VFailureQuintic;
		
		private System.Nullable<bool> _BackupOnce;
		
		private System.Nullable<bool> _BackupQuintic;
		
	#region 可扩展性方法定义
	partial void OnLoaded();
	partial void OnValidate(System.Data.Linq.ChangeAction action);
	partial void OnCreated();
	partial void OnIDChanging(System.Guid value);
	partial void OnIDChanged();
	partial void OnStationIDChanging(string value);
	partial void OnStationIDChanged();
	partial void OnDateTimeChanging(System.DateTime value);
	partial void OnDateTimeChanged();
	partial void OnPowerGridUnderVolOnceChanging(System.Nullable<bool> value);
	partial void OnPowerGridUnderVolOnceChanged();
	partial void OnPowerGridUnderVolQuinticChanging(System.Nullable<bool> value);
	partial void OnPowerGridUnderVolQuinticChanged();
	partial void OnLowPowerFailureOnceChanging(System.Nullable<bool> value);
	partial void OnLowPowerFailureOnceChanged();
	partial void OnLowPowerFailureQuinticChanging(System.Nullable<bool> value);
	partial void OnLowPowerFailureQuinticChanged();
	partial void OnFilaVolFailureOnceChanging(System.Nullable<bool> value);
	partial void OnFilaVolFailureOnceChanged();
	partial void OnFilaVolFailureQuinticChanging(System.Nullable<bool> value);
	partial void OnFilaVolFailureQuinticChanged();
	partial void OnTitPumpFailureOnceChanging(System.Nullable<bool> value);
	partial void OnTitPumpFailureOnceChanged();
	partial void OnTitPumpFailureQuinticChanging(System.Nullable<bool> value);
	partial void OnTitPumpFailureQuinticChanged();
	partial void OnFocusCoilVolFailureOnceChanging(System.Nullable<bool> value);
	partial void OnFocusCoilVolFailureOnceChanged();
	partial void OnFocusCoilVolFailureQuinticChanging(System.Nullable<bool> value);
	partial void OnFocusCoilVolFailureQuinticChanged();
	partial void OnTransmitOverVolOnceChanging(System.Nullable<bool> value);
	partial void OnTransmitOverVolOnceChanged();
	partial void OnTransmitOverVolQuinticChanging(System.Nullable<bool> value);
	partial void OnTransmitOverVolQuinticChanged();
	partial void OnTransmitOverCurOnceChanging(System.Nullable<bool> value);
	partial void OnTransmitOverCurOnceChanged();
	partial void OnTransmitOverCurQuinticChanging(System.Nullable<bool> value);
	partial void OnTransmitOverCurQuinticChanged();
	partial void OnFocusCoilCurFailureOnceChanging(System.Nullable<bool> value);
	partial void OnFocusCoilCurFailureOnceChanged();
	partial void OnFocusCoilCurFailureQuinticChanging(System.Nullable<bool> value);
	partial void OnFocusCoilCurFailureQuinticChanged();
	partial void OnFocusCoilAirFlowFailureOnceChanging(System.Nullable<bool> value);
	partial void OnFocusCoilAirFlowFailureOnceChanged();
	partial void OnFocusCoilAirFlowFailureQuinticChanging(System.Nullable<bool> value);
	partial void OnFocusCoilAirFlowFailureQuinticChanged();
	partial void OnTriggerFailureOnceChanging(System.Nullable<bool> value);
	partial void OnTriggerFailureOnceChanged();
	partial void OnTriggerFailureQuinticChanging(System.Nullable<bool> value);
	partial void OnTriggerFailureQuinticChanged();
	partial void OnChargingFeedbackFlowRectifierUnderVolOnceChanging(System.Nullable<bool> value);
	partial void OnChargingFeedbackFlowRectifierUnderVolOnceChanged();
	partial void OnChargingFeedbackFlowRectifierUnderVolQuinticChanging(System.Nullable<bool> value);
	partial void OnChargingFeedbackFlowRectifierUnderVolQuinticChanged();
	partial void OnChargingFailureOnceChanging(System.Nullable<bool> value);
	partial void OnChargingFailureOnceChanged();
	partial void OnChargingFailureQuinticChanging(System.Nullable<bool> value);
	partial void OnChargingFailureQuinticChanged();
	partial void OnModulatorOverOnceChanging(System.Nullable<bool> value);
	partial void OnModulatorOverOnceChanged();
	partial void OnModulatorOverQuinticChanging(System.Nullable<bool> value);
	partial void OnModulatorOverQuinticChanged();
	partial void OnModulatorNegPeakOverOnceChanging(System.Nullable<bool> value);
	partial void OnModulatorNegPeakOverOnceChanged();
	partial void OnModulatorNegPeakOverQuinticChanging(System.Nullable<bool> value);
	partial void OnModulatorNegPeakOverQuinticChanged();
	partial void OnModulatorSwitchFailureOnceChanging(System.Nullable<bool> value);
	partial void OnModulatorSwitchFailureOnceChanged();
	partial void OnModulatorSwitchFailureQuinticChanging(System.Nullable<bool> value);
	partial void OnModulatorSwitchFailureQuinticChanged();
	partial void OnKlystronOverCurOnceChanging(System.Nullable<bool> value);
	partial void OnKlystronOverCurOnceChanged();
	partial void OnKlystronOverCurQuinticChanging(System.Nullable<bool> value);
	partial void OnKlystronOverCurQuinticChanged();
	partial void OnKlystronFilaFailureOnceChanging(System.Nullable<bool> value);
	partial void OnKlystronFilaFailureOnceChanged();
	partial void OnKlystronFilaFailureQuinticChanging(System.Nullable<bool> value);
	partial void OnKlystronFilaFailureQuinticChanged();
	partial void OnKlystronTitPumpFailureOnceChanging(System.Nullable<bool> value);
	partial void OnKlystronTitPumpFailureOnceChanged();
	partial void OnKlystronTitPumpFailureQuinticChanging(System.Nullable<bool> value);
	partial void OnKlystronTitPumpFailureQuinticChanged();
	partial void OnKlystronAirTempAlarmOnceChanging(System.Nullable<bool> value);
	partial void OnKlystronAirTempAlarmOnceChanged();
	partial void OnKlystronAirTempAlarmQuinticChanging(System.Nullable<bool> value);
	partial void OnKlystronAirTempAlarmQuinticChanged();
	partial void OnKlystronAirFlowAlarmOnceChanging(System.Nullable<bool> value);
	partial void OnKlystronAirFlowAlarmOnceChanged();
	partial void OnKlystronAirFlowAlarmQuinticChanging(System.Nullable<bool> value);
	partial void OnKlystronAirFlowAlarmQuinticChanged();
	partial void OnWaveGuidPressAlarmOnceChanging(System.Nullable<bool> value);
	partial void OnWaveGuidPressAlarmOnceChanged();
	partial void OnWaveGuidPressAlarmQuinticChanging(System.Nullable<bool> value);
	partial void OnWaveGuidPressAlarmQuinticChanged();
	partial void OnWaveGuidArcAlarmOnceChanging(System.Nullable<bool> value);
	partial void OnWaveGuidArcAlarmOnceChanged();
	partial void OnWaveGuidArcAlarmQuinticChanging(System.Nullable<bool> value);
	partial void OnWaveGuidArcAlarmQuinticChanged();
	partial void OnTankLevelAlarmOnceChanging(System.Nullable<bool> value);
	partial void OnTankLevelAlarmOnceChanged();
	partial void OnTankLevelAlarmQuinticChanging(System.Nullable<bool> value);
	partial void OnTankLevelAlarmQuinticChanged();
	partial void OnTankTempAlarmOnceChanging(System.Nullable<bool> value);
	partial void OnTankTempAlarmOnceChanged();
	partial void OnTankTempAlarmQuinticChanging(System.Nullable<bool> value);
	partial void OnTankTempAlarmQuinticChanged();
	partial void OnAntennaWaveGuidChainChanging(System.Nullable<bool> value);
	partial void OnAntennaWaveGuidChainChanged();
	partial void OnAntennaCirculatorOverHeatChanging(System.Nullable<bool> value);
	partial void OnAntennaCirculatorOverHeatChanged();
	partial void OnRackDoorChainOnceChanging(System.Nullable<bool> value);
	partial void OnRackDoorChainOnceChanged();
	partial void OnRackDoorChainQuinticChanging(System.Nullable<bool> value);
	partial void OnRackDoorChainQuinticChanged();
	partial void OnRackAirTempAlarmOnceChanging(System.Nullable<bool> value);
	partial void OnRackAirTempAlarmOnceChanged();
	partial void OnRackAirTempAlarmQuinticChanging(System.Nullable<bool> value);
	partial void OnRackAirTempAlarmQuinticChanged();
	partial void OnRackAirFlowAlarmOnceChanging(System.Nullable<bool> value);
	partial void OnRackAirFlowAlarmOnceChanged();
	partial void OnRackAirFlowAlarmQuinticChanging(System.Nullable<bool> value);
	partial void OnRackAirFlowAlarmQuinticChanged();
	partial void OnDutyCycleOverOnceChanging(System.Nullable<bool> value);
	partial void OnDutyCycleOverOnceChanged();
	partial void OnDutyCycleOverQuinticChanging(System.Nullable<bool> value);
	partial void OnDutyCycleOverQuinticChanged();
	partial void OnWaveGuidPressHumidityReqChanging(System.Nullable<bool> value);
	partial void OnWaveGuidPressHumidityReqChanged();
	partial void OnModulatorSwitchReqChanging(System.Nullable<bool> value);
	partial void OnModulatorSwitchReqChanged();
	partial void OnAfterChargingFairChanging(System.Nullable<bool> value);
	partial void OnAfterChargingFairChanged();
	partial void On_510VFailureOnceChanging(System.Nullable<bool> value);
	partial void On_510VFailureOnceChanged();
	partial void On_510VFailureQuinticChanging(System.Nullable<bool> value);
	partial void On_510VFailureQuinticChanged();
	partial void OnBackupOnceChanging(System.Nullable<bool> value);
	partial void OnBackupOnceChanged();
	partial void OnBackupQuinticChanging(System.Nullable<bool> value);
	partial void OnBackupQuinticChanged();
	#endregion
		
		public AlarmStatusTable()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StationID", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string StationID
		{
			get
			{
				return this._StationID;
			}
			set
			{
				if ((this._StationID != value))
				{
					this.OnStationIDChanging(value);
					this.SendPropertyChanging();
					this._StationID = value;
					this.SendPropertyChanged("StationID");
					this.OnStationIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTime", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime DateTime
		{
			get
			{
				return this._DateTime;
			}
			set
			{
				if ((this._DateTime != value))
				{
					this.OnDateTimeChanging(value);
					this.SendPropertyChanging();
					this._DateTime = value;
					this.SendPropertyChanged("DateTime");
					this.OnDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PowerGridUnderVolOnce", DbType="Bit")]
		public System.Nullable<bool> PowerGridUnderVolOnce
		{
			get
			{
				return this._PowerGridUnderVolOnce;
			}
			set
			{
				if ((this._PowerGridUnderVolOnce != value))
				{
					this.OnPowerGridUnderVolOnceChanging(value);
					this.SendPropertyChanging();
					this._PowerGridUnderVolOnce = value;
					this.SendPropertyChanged("PowerGridUnderVolOnce");
					this.OnPowerGridUnderVolOnceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PowerGridUnderVolQuintic", DbType="Bit")]
		public System.Nullable<bool> PowerGridUnderVolQuintic
		{
			get
			{
				return this._PowerGridUnderVolQuintic;
			}
			set
			{
				if ((this._PowerGridUnderVolQuintic != value))
				{
					this.OnPowerGridUnderVolQuinticChanging(value);
					this.SendPropertyChanging();
					this._PowerGridUnderVolQuintic = value;
					this.SendPropertyChanged("PowerGridUnderVolQuintic");
					this.OnPowerGridUnderVolQuinticChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LowPowerFailureOnce", DbType="Bit")]
		public System.Nullable<bool> LowPowerFailureOnce
		{
			get
			{
				return this._LowPowerFailureOnce;
			}
			set
			{
				if ((this._LowPowerFailureOnce != value))
				{
					this.OnLowPowerFailureOnceChanging(value);
					this.SendPropertyChanging();
					this._LowPowerFailureOnce = value;
					this.SendPropertyChanged("LowPowerFailureOnce");
					this.OnLowPowerFailureOnceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LowPowerFailureQuintic", DbType="Bit")]
		public System.Nullable<bool> LowPowerFailureQuintic
		{
			get
			{
				return this._LowPowerFailureQuintic;
			}
			set
			{
				if ((this._LowPowerFailureQuintic != value))
				{
					this.OnLowPowerFailureQuinticChanging(value);
					this.SendPropertyChanging();
					this._LowPowerFailureQuintic = value;
					this.SendPropertyChanged("LowPowerFailureQuintic");
					this.OnLowPowerFailureQuinticChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FilaVolFailureOnce", DbType="Bit")]
		public System.Nullable<bool> FilaVolFailureOnce
		{
			get
			{
				return this._FilaVolFailureOnce;
			}
			set
			{
				if ((this._FilaVolFailureOnce != value))
				{
					this.OnFilaVolFailureOnceChanging(value);
					this.SendPropertyChanging();
					this._FilaVolFailureOnce = value;
					this.SendPropertyChanged("FilaVolFailureOnce");
					this.OnFilaVolFailureOnceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FilaVolFailureQuintic", DbType="Bit")]
		public System.Nullable<bool> FilaVolFailureQuintic
		{
			get
			{
				return this._FilaVolFailureQuintic;
			}
			set
			{
				if ((this._FilaVolFailureQuintic != value))
				{
					this.OnFilaVolFailureQuinticChanging(value);
					this.SendPropertyChanging();
					this._FilaVolFailureQuintic = value;
					this.SendPropertyChanged("FilaVolFailureQuintic");
					this.OnFilaVolFailureQuinticChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TitPumpFailureOnce", DbType="Bit")]
		public System.Nullable<bool> TitPumpFailureOnce
		{
			get
			{
				return this._TitPumpFailureOnce;
			}
			set
			{
				if ((this._TitPumpFailureOnce != value))
				{
					this.OnTitPumpFailureOnceChanging(value);
					this.SendPropertyChanging();
					this._TitPumpFailureOnce = value;
					this.SendPropertyChanged("TitPumpFailureOnce");
					this.OnTitPumpFailureOnceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TitPumpFailureQuintic", DbType="Bit")]
		public System.Nullable<bool> TitPumpFailureQuintic
		{
			get
			{
				return this._TitPumpFailureQuintic;
			}
			set
			{
				if ((this._TitPumpFailureQuintic != value))
				{
					this.OnTitPumpFailureQuinticChanging(value);
					this.SendPropertyChanging();
					this._TitPumpFailureQuintic = value;
					this.SendPropertyChanged("TitPumpFailureQuintic");
					this.OnTitPumpFailureQuinticChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FocusCoilVolFailureOnce", DbType="Bit")]
		public System.Nullable<bool> FocusCoilVolFailureOnce
		{
			get
			{
				return this._FocusCoilVolFailureOnce;
			}
			set
			{
				if ((this._FocusCoilVolFailureOnce != value))
				{
					this.OnFocusCoilVolFailureOnceChanging(value);
					this.SendPropertyChanging();
					this._FocusCoilVolFailureOnce = value;
					this.SendPropertyChanged("FocusCoilVolFailureOnce");
					this.OnFocusCoilVolFailureOnceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FocusCoilVolFailureQuintic", DbType="Bit")]
		public System.Nullable<bool> FocusCoilVolFailureQuintic
		{
			get
			{
				return this._FocusCoilVolFailureQuintic;
			}
			set
			{
				if ((this._FocusCoilVolFailureQuintic != value))
				{
					this.OnFocusCoilVolFailureQuinticChanging(value);
					this.SendPropertyChanging();
					this._FocusCoilVolFailureQuintic = value;
					this.SendPropertyChanged("FocusCoilVolFailureQuintic");
					this.OnFocusCoilVolFailureQuinticChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransmitOverVolOnce", DbType="Bit")]
		public System.Nullable<bool> TransmitOverVolOnce
		{
			get
			{
				return this._TransmitOverVolOnce;
			}
			set
			{
				if ((this._TransmitOverVolOnce != value))
				{
					this.OnTransmitOverVolOnceChanging(value);
					this.SendPropertyChanging();
					this._TransmitOverVolOnce = value;
					this.SendPropertyChanged("TransmitOverVolOnce");
					this.OnTransmitOverVolOnceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransmitOverVolQuintic", DbType="Bit")]
		public System.Nullable<bool> TransmitOverVolQuintic
		{
			get
			{
				return this._TransmitOverVolQuintic;
			}
			set
			{
				if ((this._TransmitOverVolQuintic != value))
				{
					this.OnTransmitOverVolQuinticChanging(value);
					this.SendPropertyChanging();
					this._TransmitOverVolQuintic = value;
					this.SendPropertyChanged("TransmitOverVolQuintic");
					this.OnTransmitOverVolQuinticChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransmitOverCurOnce", DbType="Bit")]
		public System.Nullable<bool> TransmitOverCurOnce
		{
			get
			{
				return this._TransmitOverCurOnce;
			}
			set
			{
				if ((this._TransmitOverCurOnce != value))
				{
					this.OnTransmitOverCurOnceChanging(value);
					this.SendPropertyChanging();
					this._TransmitOverCurOnce = value;
					this.SendPropertyChanged("TransmitOverCurOnce");
					this.OnTransmitOverCurOnceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransmitOverCurQuintic", DbType="Bit")]
		public System.Nullable<bool> TransmitOverCurQuintic
		{
			get
			{
				return this._TransmitOverCurQuintic;
			}
			set
			{
				if ((this._TransmitOverCurQuintic != value))
				{
					this.OnTransmitOverCurQuinticChanging(value);
					this.SendPropertyChanging();
					this._TransmitOverCurQuintic = value;
					this.SendPropertyChanged("TransmitOverCurQuintic");
					this.OnTransmitOverCurQuinticChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FocusCoilCurFailureOnce", DbType="Bit")]
		public System.Nullable<bool> FocusCoilCurFailureOnce
		{
			get
			{
				return this._FocusCoilCurFailureOnce;
			}
			set
			{
				if ((this._FocusCoilCurFailureOnce != value))
				{
					this.OnFocusCoilCurFailureOnceChanging(value);
					this.SendPropertyChanging();
					this._FocusCoilCurFailureOnce = value;
					this.SendPropertyChanged("FocusCoilCurFailureOnce");
					this.OnFocusCoilCurFailureOnceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FocusCoilCurFailureQuintic", DbType="Bit")]
		public System.Nullable<bool> FocusCoilCurFailureQuintic
		{
			get
			{
				return this._FocusCoilCurFailureQuintic;
			}
			set
			{
				if ((this._FocusCoilCurFailureQuintic != value))
				{
					this.OnFocusCoilCurFailureQuinticChanging(value);
					this.SendPropertyChanging();
					this._FocusCoilCurFailureQuintic = value;
					this.SendPropertyChanged("FocusCoilCurFailureQuintic");
					this.OnFocusCoilCurFailureQuinticChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FocusCoilAirFlowFailureOnce", DbType="Bit")]
		public System.Nullable<bool> FocusCoilAirFlowFailureOnce
		{
			get
			{
				return this._FocusCoilAirFlowFailureOnce;
			}
			set
			{
				if ((this._FocusCoilAirFlowFailureOnce != value))
				{
					this.OnFocusCoilAirFlowFailureOnceChanging(value);
					this.SendPropertyChanging();
					this._FocusCoilAirFlowFailureOnce = value;
					this.SendPropertyChanged("FocusCoilAirFlowFailureOnce");
					this.OnFocusCoilAirFlowFailureOnceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FocusCoilAirFlowFailureQuintic", DbType="Bit")]
		public System.Nullable<bool> FocusCoilAirFlowFailureQuintic
		{
			get
			{
				return this._FocusCoilAirFlowFailureQuintic;
			}
			set
			{
				if ((this._FocusCoilAirFlowFailureQuintic != value))
				{
					this.OnFocusCoilAirFlowFailureQuinticChanging(value);
					this.SendPropertyChanging();
					this._FocusCoilAirFlowFailureQuintic = value;
					this.SendPropertyChanged("FocusCoilAirFlowFailureQuintic");
					this.OnFocusCoilAirFlowFailureQuinticChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TriggerFailureOnce", DbType="Bit")]
		public System.Nullable<bool> TriggerFailureOnce
		{
			get
			{
				return this._TriggerFailureOnce;
			}
			set
			{
				if ((this._TriggerFailureOnce != value))
				{
					this.OnTriggerFailureOnceChanging(value);
					this.SendPropertyChanging();
					this._TriggerFailureOnce = value;
					this.SendPropertyChanged("TriggerFailureOnce");
					this.OnTriggerFailureOnceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TriggerFailureQuintic", DbType="Bit")]
		public System.Nullable<bool> TriggerFailureQuintic
		{
			get
			{
				return this._TriggerFailureQuintic;
			}
			set
			{
				if ((this._TriggerFailureQuintic != value))
				{
					this.OnTriggerFailureQuinticChanging(value);
					this.SendPropertyChanging();
					this._TriggerFailureQuintic = value;
					this.SendPropertyChanged("TriggerFailureQuintic");
					this.OnTriggerFailureQuinticChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChargingFeedbackFlowRectifierUnderVolOnce", DbType="Bit")]
		public System.Nullable<bool> ChargingFeedbackFlowRectifierUnderVolOnce
		{
			get
			{
				return this._ChargingFeedbackFlowRectifierUnderVolOnce;
			}
			set
			{
				if ((this._ChargingFeedbackFlowRectifierUnderVolOnce != value))
				{
					this.OnChargingFeedbackFlowRectifierUnderVolOnceChanging(value);
					this.SendPropertyChanging();
					this._ChargingFeedbackFlowRectifierUnderVolOnce = value;
					this.SendPropertyChanged("ChargingFeedbackFlowRectifierUnderVolOnce");
					this.OnChargingFeedbackFlowRectifierUnderVolOnceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChargingFeedbackFlowRectifierUnderVolQuintic", DbType="Bit")]
		public System.Nullable<bool> ChargingFeedbackFlowRectifierUnderVolQuintic
		{
			get
			{
				return this._ChargingFeedbackFlowRectifierUnderVolQuintic;
			}
			set
			{
				if ((this._ChargingFeedbackFlowRectifierUnderVolQuintic != value))
				{
					this.OnChargingFeedbackFlowRectifierUnderVolQuinticChanging(value);
					this.SendPropertyChanging();
					this._ChargingFeedbackFlowRectifierUnderVolQuintic = value;
					this.SendPropertyChanged("ChargingFeedbackFlowRectifierUnderVolQuintic");
					this.OnChargingFeedbackFlowRectifierUnderVolQuinticChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChargingFailureOnce", DbType="Bit")]
		public System.Nullable<bool> ChargingFailureOnce
		{
			get
			{
				return this._ChargingFailureOnce;
			}
			set
			{
				if ((this._ChargingFailureOnce != value))
				{
					this.OnChargingFailureOnceChanging(value);
					this.SendPropertyChanging();
					this._ChargingFailureOnce = value;
					this.SendPropertyChanged("ChargingFailureOnce");
					this.OnChargingFailureOnceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChargingFailureQuintic", DbType="Bit")]
		public System.Nullable<bool> ChargingFailureQuintic
		{
			get
			{
				return this._ChargingFailureQuintic;
			}
			set
			{
				if ((this._ChargingFailureQuintic != value))
				{
					this.OnChargingFailureQuinticChanging(value);
					this.SendPropertyChanging();
					this._ChargingFailureQuintic = value;
					this.SendPropertyChanged("ChargingFailureQuintic");
					this.OnChargingFailureQuinticChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModulatorOverOnce", DbType="Bit")]
		public System.Nullable<bool> ModulatorOverOnce
		{
			get
			{
				return this._ModulatorOverOnce;
			}
			set
			{
				if ((this._ModulatorOverOnce != value))
				{
					this.OnModulatorOverOnceChanging(value);
					this.SendPropertyChanging();
					this._ModulatorOverOnce = value;
					this.SendPropertyChanged("ModulatorOverOnce");
					this.OnModulatorOverOnceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModulatorOverQuintic", DbType="Bit")]
		public System.Nullable<bool> ModulatorOverQuintic
		{
			get
			{
				return this._ModulatorOverQuintic;
			}
			set
			{
				if ((this._ModulatorOverQuintic != value))
				{
					this.OnModulatorOverQuinticChanging(value);
					this.SendPropertyChanging();
					this._ModulatorOverQuintic = value;
					this.SendPropertyChanged("ModulatorOverQuintic");
					this.OnModulatorOverQuinticChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModulatorNegPeakOverOnce", DbType="Bit")]
		public System.Nullable<bool> ModulatorNegPeakOverOnce
		{
			get
			{
				return this._ModulatorNegPeakOverOnce;
			}
			set
			{
				if ((this._ModulatorNegPeakOverOnce != value))
				{
					this.OnModulatorNegPeakOverOnceChanging(value);
					this.SendPropertyChanging();
					this._ModulatorNegPeakOverOnce = value;
					this.SendPropertyChanged("ModulatorNegPeakOverOnce");
					this.OnModulatorNegPeakOverOnceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModulatorNegPeakOverQuintic", DbType="Bit")]
		public System.Nullable<bool> ModulatorNegPeakOverQuintic
		{
			get
			{
				return this._ModulatorNegPeakOverQuintic;
			}
			set
			{
				if ((this._ModulatorNegPeakOverQuintic != value))
				{
					this.OnModulatorNegPeakOverQuinticChanging(value);
					this.SendPropertyChanging();
					this._ModulatorNegPeakOverQuintic = value;
					this.SendPropertyChanged("ModulatorNegPeakOverQuintic");
					this.OnModulatorNegPeakOverQuinticChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModulatorSwitchFailureOnce", DbType="Bit")]
		public System.Nullable<bool> ModulatorSwitchFailureOnce
		{
			get
			{
				return this._ModulatorSwitchFailureOnce;
			}
			set
			{
				if ((this._ModulatorSwitchFailureOnce != value))
				{
					this.OnModulatorSwitchFailureOnceChanging(value);
					this.SendPropertyChanging();
					this._ModulatorSwitchFailureOnce = value;
					this.SendPropertyChanged("ModulatorSwitchFailureOnce");
					this.OnModulatorSwitchFailureOnceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModulatorSwitchFailureQuintic", DbType="Bit")]
		public System.Nullable<bool> ModulatorSwitchFailureQuintic
		{
			get
			{
				return this._ModulatorSwitchFailureQuintic;
			}
			set
			{
				if ((this._ModulatorSwitchFailureQuintic != value))
				{
					this.OnModulatorSwitchFailureQuinticChanging(value);
					this.SendPropertyChanging();
					this._ModulatorSwitchFailureQuintic = value;
					this.SendPropertyChanged("ModulatorSwitchFailureQuintic");
					this.OnModulatorSwitchFailureQuinticChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KlystronOverCurOnce", DbType="Bit")]
		public System.Nullable<bool> KlystronOverCurOnce
		{
			get
			{
				return this._KlystronOverCurOnce;
			}
			set
			{
				if ((this._KlystronOverCurOnce != value))
				{
					this.OnKlystronOverCurOnceChanging(value);
					this.SendPropertyChanging();
					this._KlystronOverCurOnce = value;
					this.SendPropertyChanged("KlystronOverCurOnce");
					this.OnKlystronOverCurOnceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KlystronOverCurQuintic", DbType="Bit")]
		public System.Nullable<bool> KlystronOverCurQuintic
		{
			get
			{
				return this._KlystronOverCurQuintic;
			}
			set
			{
				if ((this._KlystronOverCurQuintic != value))
				{
					this.OnKlystronOverCurQuinticChanging(value);
					this.SendPropertyChanging();
					this._KlystronOverCurQuintic = value;
					this.SendPropertyChanged("KlystronOverCurQuintic");
					this.OnKlystronOverCurQuinticChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KlystronFilaFailureOnce", DbType="Bit")]
		public System.Nullable<bool> KlystronFilaFailureOnce
		{
			get
			{
				return this._KlystronFilaFailureOnce;
			}
			set
			{
				if ((this._KlystronFilaFailureOnce != value))
				{
					this.OnKlystronFilaFailureOnceChanging(value);
					this.SendPropertyChanging();
					this._KlystronFilaFailureOnce = value;
					this.SendPropertyChanged("KlystronFilaFailureOnce");
					this.OnKlystronFilaFailureOnceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KlystronFilaFailureQuintic", DbType="Bit")]
		public System.Nullable<bool> KlystronFilaFailureQuintic
		{
			get
			{
				return this._KlystronFilaFailureQuintic;
			}
			set
			{
				if ((this._KlystronFilaFailureQuintic != value))
				{
					this.OnKlystronFilaFailureQuinticChanging(value);
					this.SendPropertyChanging();
					this._KlystronFilaFailureQuintic = value;
					this.SendPropertyChanged("KlystronFilaFailureQuintic");
					this.OnKlystronFilaFailureQuinticChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KlystronTitPumpFailureOnce", DbType="Bit")]
		public System.Nullable<bool> KlystronTitPumpFailureOnce
		{
			get
			{
				return this._KlystronTitPumpFailureOnce;
			}
			set
			{
				if ((this._KlystronTitPumpFailureOnce != value))
				{
					this.OnKlystronTitPumpFailureOnceChanging(value);
					this.SendPropertyChanging();
					this._KlystronTitPumpFailureOnce = value;
					this.SendPropertyChanged("KlystronTitPumpFailureOnce");
					this.OnKlystronTitPumpFailureOnceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KlystronTitPumpFailureQuintic", DbType="Bit")]
		public System.Nullable<bool> KlystronTitPumpFailureQuintic
		{
			get
			{
				return this._KlystronTitPumpFailureQuintic;
			}
			set
			{
				if ((this._KlystronTitPumpFailureQuintic != value))
				{
					this.OnKlystronTitPumpFailureQuinticChanging(value);
					this.SendPropertyChanging();
					this._KlystronTitPumpFailureQuintic = value;
					this.SendPropertyChanged("KlystronTitPumpFailureQuintic");
					this.OnKlystronTitPumpFailureQuinticChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KlystronAirTempAlarmOnce", DbType="Bit")]
		public System.Nullable<bool> KlystronAirTempAlarmOnce
		{
			get
			{
				return this._KlystronAirTempAlarmOnce;
			}
			set
			{
				if ((this._KlystronAirTempAlarmOnce != value))
				{
					this.OnKlystronAirTempAlarmOnceChanging(value);
					this.SendPropertyChanging();
					this._KlystronAirTempAlarmOnce = value;
					this.SendPropertyChanged("KlystronAirTempAlarmOnce");
					this.OnKlystronAirTempAlarmOnceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KlystronAirTempAlarmQuintic", DbType="Bit")]
		public System.Nullable<bool> KlystronAirTempAlarmQuintic
		{
			get
			{
				return this._KlystronAirTempAlarmQuintic;
			}
			set
			{
				if ((this._KlystronAirTempAlarmQuintic != value))
				{
					this.OnKlystronAirTempAlarmQuinticChanging(value);
					this.SendPropertyChanging();
					this._KlystronAirTempAlarmQuintic = value;
					this.SendPropertyChanged("KlystronAirTempAlarmQuintic");
					this.OnKlystronAirTempAlarmQuinticChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KlystronAirFlowAlarmOnce", DbType="Bit")]
		public System.Nullable<bool> KlystronAirFlowAlarmOnce
		{
			get
			{
				return this._KlystronAirFlowAlarmOnce;
			}
			set
			{
				if ((this._KlystronAirFlowAlarmOnce != value))
				{
					this.OnKlystronAirFlowAlarmOnceChanging(value);
					this.SendPropertyChanging();
					this._KlystronAirFlowAlarmOnce = value;
					this.SendPropertyChanged("KlystronAirFlowAlarmOnce");
					this.OnKlystronAirFlowAlarmOnceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KlystronAirFlowAlarmQuintic", DbType="Bit")]
		public System.Nullable<bool> KlystronAirFlowAlarmQuintic
		{
			get
			{
				return this._KlystronAirFlowAlarmQuintic;
			}
			set
			{
				if ((this._KlystronAirFlowAlarmQuintic != value))
				{
					this.OnKlystronAirFlowAlarmQuinticChanging(value);
					this.SendPropertyChanging();
					this._KlystronAirFlowAlarmQuintic = value;
					this.SendPropertyChanged("KlystronAirFlowAlarmQuintic");
					this.OnKlystronAirFlowAlarmQuinticChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WaveGuidPressAlarmOnce", DbType="Bit")]
		public System.Nullable<bool> WaveGuidPressAlarmOnce
		{
			get
			{
				return this._WaveGuidPressAlarmOnce;
			}
			set
			{
				if ((this._WaveGuidPressAlarmOnce != value))
				{
					this.OnWaveGuidPressAlarmOnceChanging(value);
					this.SendPropertyChanging();
					this._WaveGuidPressAlarmOnce = value;
					this.SendPropertyChanged("WaveGuidPressAlarmOnce");
					this.OnWaveGuidPressAlarmOnceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WaveGuidPressAlarmQuintic", DbType="Bit")]
		public System.Nullable<bool> WaveGuidPressAlarmQuintic
		{
			get
			{
				return this._WaveGuidPressAlarmQuintic;
			}
			set
			{
				if ((this._WaveGuidPressAlarmQuintic != value))
				{
					this.OnWaveGuidPressAlarmQuinticChanging(value);
					this.SendPropertyChanging();
					this._WaveGuidPressAlarmQuintic = value;
					this.SendPropertyChanged("WaveGuidPressAlarmQuintic");
					this.OnWaveGuidPressAlarmQuinticChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WaveGuidArcAlarmOnce", DbType="Bit")]
		public System.Nullable<bool> WaveGuidArcAlarmOnce
		{
			get
			{
				return this._WaveGuidArcAlarmOnce;
			}
			set
			{
				if ((this._WaveGuidArcAlarmOnce != value))
				{
					this.OnWaveGuidArcAlarmOnceChanging(value);
					this.SendPropertyChanging();
					this._WaveGuidArcAlarmOnce = value;
					this.SendPropertyChanged("WaveGuidArcAlarmOnce");
					this.OnWaveGuidArcAlarmOnceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WaveGuidArcAlarmQuintic", DbType="Bit")]
		public System.Nullable<bool> WaveGuidArcAlarmQuintic
		{
			get
			{
				return this._WaveGuidArcAlarmQuintic;
			}
			set
			{
				if ((this._WaveGuidArcAlarmQuintic != value))
				{
					this.OnWaveGuidArcAlarmQuinticChanging(value);
					this.SendPropertyChanging();
					this._WaveGuidArcAlarmQuintic = value;
					this.SendPropertyChanged("WaveGuidArcAlarmQuintic");
					this.OnWaveGuidArcAlarmQuinticChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TankLevelAlarmOnce", DbType="Bit")]
		public System.Nullable<bool> TankLevelAlarmOnce
		{
			get
			{
				return this._TankLevelAlarmOnce;
			}
			set
			{
				if ((this._TankLevelAlarmOnce != value))
				{
					this.OnTankLevelAlarmOnceChanging(value);
					this.SendPropertyChanging();
					this._TankLevelAlarmOnce = value;
					this.SendPropertyChanged("TankLevelAlarmOnce");
					this.OnTankLevelAlarmOnceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TankLevelAlarmQuintic", DbType="Bit")]
		public System.Nullable<bool> TankLevelAlarmQuintic
		{
			get
			{
				return this._TankLevelAlarmQuintic;
			}
			set
			{
				if ((this._TankLevelAlarmQuintic != value))
				{
					this.OnTankLevelAlarmQuinticChanging(value);
					this.SendPropertyChanging();
					this._TankLevelAlarmQuintic = value;
					this.SendPropertyChanged("TankLevelAlarmQuintic");
					this.OnTankLevelAlarmQuinticChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TankTempAlarmOnce", DbType="Bit")]
		public System.Nullable<bool> TankTempAlarmOnce
		{
			get
			{
				return this._TankTempAlarmOnce;
			}
			set
			{
				if ((this._TankTempAlarmOnce != value))
				{
					this.OnTankTempAlarmOnceChanging(value);
					this.SendPropertyChanging();
					this._TankTempAlarmOnce = value;
					this.SendPropertyChanged("TankTempAlarmOnce");
					this.OnTankTempAlarmOnceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TankTempAlarmQuintic", DbType="Bit")]
		public System.Nullable<bool> TankTempAlarmQuintic
		{
			get
			{
				return this._TankTempAlarmQuintic;
			}
			set
			{
				if ((this._TankTempAlarmQuintic != value))
				{
					this.OnTankTempAlarmQuinticChanging(value);
					this.SendPropertyChanging();
					this._TankTempAlarmQuintic = value;
					this.SendPropertyChanged("TankTempAlarmQuintic");
					this.OnTankTempAlarmQuinticChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AntennaWaveGuidChain", DbType="Bit")]
		public System.Nullable<bool> AntennaWaveGuidChain
		{
			get
			{
				return this._AntennaWaveGuidChain;
			}
			set
			{
				if ((this._AntennaWaveGuidChain != value))
				{
					this.OnAntennaWaveGuidChainChanging(value);
					this.SendPropertyChanging();
					this._AntennaWaveGuidChain = value;
					this.SendPropertyChanged("AntennaWaveGuidChain");
					this.OnAntennaWaveGuidChainChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AntennaCirculatorOverHeat", DbType="Bit")]
		public System.Nullable<bool> AntennaCirculatorOverHeat
		{
			get
			{
				return this._AntennaCirculatorOverHeat;
			}
			set
			{
				if ((this._AntennaCirculatorOverHeat != value))
				{
					this.OnAntennaCirculatorOverHeatChanging(value);
					this.SendPropertyChanging();
					this._AntennaCirculatorOverHeat = value;
					this.SendPropertyChanged("AntennaCirculatorOverHeat");
					this.OnAntennaCirculatorOverHeatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RackDoorChainOnce", DbType="Bit")]
		public System.Nullable<bool> RackDoorChainOnce
		{
			get
			{
				return this._RackDoorChainOnce;
			}
			set
			{
				if ((this._RackDoorChainOnce != value))
				{
					this.OnRackDoorChainOnceChanging(value);
					this.SendPropertyChanging();
					this._RackDoorChainOnce = value;
					this.SendPropertyChanged("RackDoorChainOnce");
					this.OnRackDoorChainOnceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RackDoorChainQuintic", DbType="Bit")]
		public System.Nullable<bool> RackDoorChainQuintic
		{
			get
			{
				return this._RackDoorChainQuintic;
			}
			set
			{
				if ((this._RackDoorChainQuintic != value))
				{
					this.OnRackDoorChainQuinticChanging(value);
					this.SendPropertyChanging();
					this._RackDoorChainQuintic = value;
					this.SendPropertyChanged("RackDoorChainQuintic");
					this.OnRackDoorChainQuinticChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RackAirTempAlarmOnce", DbType="Bit")]
		public System.Nullable<bool> RackAirTempAlarmOnce
		{
			get
			{
				return this._RackAirTempAlarmOnce;
			}
			set
			{
				if ((this._RackAirTempAlarmOnce != value))
				{
					this.OnRackAirTempAlarmOnceChanging(value);
					this.SendPropertyChanging();
					this._RackAirTempAlarmOnce = value;
					this.SendPropertyChanged("RackAirTempAlarmOnce");
					this.OnRackAirTempAlarmOnceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RackAirTempAlarmQuintic", DbType="Bit")]
		public System.Nullable<bool> RackAirTempAlarmQuintic
		{
			get
			{
				return this._RackAirTempAlarmQuintic;
			}
			set
			{
				if ((this._RackAirTempAlarmQuintic != value))
				{
					this.OnRackAirTempAlarmQuinticChanging(value);
					this.SendPropertyChanging();
					this._RackAirTempAlarmQuintic = value;
					this.SendPropertyChanged("RackAirTempAlarmQuintic");
					this.OnRackAirTempAlarmQuinticChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RackAirFlowAlarmOnce", DbType="Bit")]
		public System.Nullable<bool> RackAirFlowAlarmOnce
		{
			get
			{
				return this._RackAirFlowAlarmOnce;
			}
			set
			{
				if ((this._RackAirFlowAlarmOnce != value))
				{
					this.OnRackAirFlowAlarmOnceChanging(value);
					this.SendPropertyChanging();
					this._RackAirFlowAlarmOnce = value;
					this.SendPropertyChanged("RackAirFlowAlarmOnce");
					this.OnRackAirFlowAlarmOnceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RackAirFlowAlarmQuintic", DbType="Bit")]
		public System.Nullable<bool> RackAirFlowAlarmQuintic
		{
			get
			{
				return this._RackAirFlowAlarmQuintic;
			}
			set
			{
				if ((this._RackAirFlowAlarmQuintic != value))
				{
					this.OnRackAirFlowAlarmQuinticChanging(value);
					this.SendPropertyChanging();
					this._RackAirFlowAlarmQuintic = value;
					this.SendPropertyChanged("RackAirFlowAlarmQuintic");
					this.OnRackAirFlowAlarmQuinticChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DutyCycleOverOnce", DbType="Bit")]
		public System.Nullable<bool> DutyCycleOverOnce
		{
			get
			{
				return this._DutyCycleOverOnce;
			}
			set
			{
				if ((this._DutyCycleOverOnce != value))
				{
					this.OnDutyCycleOverOnceChanging(value);
					this.SendPropertyChanging();
					this._DutyCycleOverOnce = value;
					this.SendPropertyChanged("DutyCycleOverOnce");
					this.OnDutyCycleOverOnceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DutyCycleOverQuintic", DbType="Bit")]
		public System.Nullable<bool> DutyCycleOverQuintic
		{
			get
			{
				return this._DutyCycleOverQuintic;
			}
			set
			{
				if ((this._DutyCycleOverQuintic != value))
				{
					this.OnDutyCycleOverQuinticChanging(value);
					this.SendPropertyChanging();
					this._DutyCycleOverQuintic = value;
					this.SendPropertyChanged("DutyCycleOverQuintic");
					this.OnDutyCycleOverQuinticChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WaveGuidPressHumidityReq", DbType="Bit")]
		public System.Nullable<bool> WaveGuidPressHumidityReq
		{
			get
			{
				return this._WaveGuidPressHumidityReq;
			}
			set
			{
				if ((this._WaveGuidPressHumidityReq != value))
				{
					this.OnWaveGuidPressHumidityReqChanging(value);
					this.SendPropertyChanging();
					this._WaveGuidPressHumidityReq = value;
					this.SendPropertyChanged("WaveGuidPressHumidityReq");
					this.OnWaveGuidPressHumidityReqChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModulatorSwitchReq", DbType="Bit")]
		public System.Nullable<bool> ModulatorSwitchReq
		{
			get
			{
				return this._ModulatorSwitchReq;
			}
			set
			{
				if ((this._ModulatorSwitchReq != value))
				{
					this.OnModulatorSwitchReqChanging(value);
					this.SendPropertyChanging();
					this._ModulatorSwitchReq = value;
					this.SendPropertyChanged("ModulatorSwitchReq");
					this.OnModulatorSwitchReqChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AfterChargingFair", DbType="Bit")]
		public System.Nullable<bool> AfterChargingFair
		{
			get
			{
				return this._AfterChargingFair;
			}
			set
			{
				if ((this._AfterChargingFair != value))
				{
					this.OnAfterChargingFairChanging(value);
					this.SendPropertyChanging();
					this._AfterChargingFair = value;
					this.SendPropertyChanged("AfterChargingFair");
					this.OnAfterChargingFairChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[510VFailureOnce]", Storage="__510VFailureOnce", DbType="Bit")]
		public System.Nullable<bool> _510VFailureOnce
		{
			get
			{
				return this.@__510VFailureOnce;
			}
			set
			{
				if ((this.@__510VFailureOnce != value))
				{
					this.On_510VFailureOnceChanging(value);
					this.SendPropertyChanging();
					this.@__510VFailureOnce = value;
					this.SendPropertyChanged("_510VFailureOnce");
					this.On_510VFailureOnceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[510VFailureQuintic]", Storage="__510VFailureQuintic", DbType="Bit")]
		public System.Nullable<bool> _510VFailureQuintic
		{
			get
			{
				return this.@__510VFailureQuintic;
			}
			set
			{
				if ((this.@__510VFailureQuintic != value))
				{
					this.On_510VFailureQuinticChanging(value);
					this.SendPropertyChanging();
					this.@__510VFailureQuintic = value;
					this.SendPropertyChanged("_510VFailureQuintic");
					this.On_510VFailureQuinticChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BackupOnce", DbType="Bit")]
		public System.Nullable<bool> BackupOnce
		{
			get
			{
				return this._BackupOnce;
			}
			set
			{
				if ((this._BackupOnce != value))
				{
					this.OnBackupOnceChanging(value);
					this.SendPropertyChanging();
					this._BackupOnce = value;
					this.SendPropertyChanged("BackupOnce");
					this.OnBackupOnceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BackupQuintic", DbType="Bit")]
		public System.Nullable<bool> BackupQuintic
		{
			get
			{
				return this._BackupQuintic;
			}
			set
			{
				if ((this._BackupQuintic != value))
				{
					this.OnBackupQuinticChanging(value);
					this.SendPropertyChanging();
					this._BackupQuintic = value;
					this.SendPropertyChanged("BackupQuintic");
					this.OnBackupQuinticChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ControlStatusTable")]
	public partial class ControlStatusTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID;
		
		private string _StationID;
		
		private System.DateTime _DateTime;
		
		private System.Nullable<bool> _LocalCtrl;
		
		private System.Nullable<bool> _RemoteCtrl;
		
		private System.Nullable<bool> _FilaSupply;
		
		private System.Nullable<bool> _Preheat;
		
		private System.Nullable<bool> _RepeatCycle;
		
		private System.Nullable<bool> _Antenna;
		
		private System.Nullable<bool> _Load;
		
		private System.Nullable<bool> _AllowOn;
		
		private System.Nullable<bool> _BroadPulse;
		
		private System.Nullable<bool> _SpikePulse;
		
		private System.Nullable<bool> _Auto;
		
		private System.Nullable<bool> _Manual;
		
		private System.Nullable<bool> _HighVolon;
		
		private System.Nullable<bool> _HighVoloff;
		
		private System.Nullable<bool> _Fault;
		
		private System.Nullable<bool> _Backup;
		
	#region 可扩展性方法定义
	partial void OnLoaded();
	partial void OnValidate(System.Data.Linq.ChangeAction action);
	partial void OnCreated();
	partial void OnIDChanging(System.Guid value);
	partial void OnIDChanged();
	partial void OnStationIDChanging(string value);
	partial void OnStationIDChanged();
	partial void OnDateTimeChanging(System.DateTime value);
	partial void OnDateTimeChanged();
	partial void OnLocalCtrlChanging(System.Nullable<bool> value);
	partial void OnLocalCtrlChanged();
	partial void OnRemoteCtrlChanging(System.Nullable<bool> value);
	partial void OnRemoteCtrlChanged();
	partial void OnFilaSupplyChanging(System.Nullable<bool> value);
	partial void OnFilaSupplyChanged();
	partial void OnPreheatChanging(System.Nullable<bool> value);
	partial void OnPreheatChanged();
	partial void OnRepeatCycleChanging(System.Nullable<bool> value);
	partial void OnRepeatCycleChanged();
	partial void OnAntennaChanging(System.Nullable<bool> value);
	partial void OnAntennaChanged();
	partial void OnLoadChanging(System.Nullable<bool> value);
	partial void OnLoadChanged();
	partial void OnAllowOnChanging(System.Nullable<bool> value);
	partial void OnAllowOnChanged();
	partial void OnBroadPulseChanging(System.Nullable<bool> value);
	partial void OnBroadPulseChanged();
	partial void OnSpikePulseChanging(System.Nullable<bool> value);
	partial void OnSpikePulseChanged();
	partial void OnAutoChanging(System.Nullable<bool> value);
	partial void OnAutoChanged();
	partial void OnManualChanging(System.Nullable<bool> value);
	partial void OnManualChanged();
	partial void OnHighVolonChanging(System.Nullable<bool> value);
	partial void OnHighVolonChanged();
	partial void OnHighVoloffChanging(System.Nullable<bool> value);
	partial void OnHighVoloffChanged();
	partial void OnFaultChanging(System.Nullable<bool> value);
	partial void OnFaultChanged();
	partial void OnBackupChanging(System.Nullable<bool> value);
	partial void OnBackupChanged();
	#endregion
		
		public ControlStatusTable()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StationID", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string StationID
		{
			get
			{
				return this._StationID;
			}
			set
			{
				if ((this._StationID != value))
				{
					this.OnStationIDChanging(value);
					this.SendPropertyChanging();
					this._StationID = value;
					this.SendPropertyChanged("StationID");
					this.OnStationIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTime", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime DateTime
		{
			get
			{
				return this._DateTime;
			}
			set
			{
				if ((this._DateTime != value))
				{
					this.OnDateTimeChanging(value);
					this.SendPropertyChanging();
					this._DateTime = value;
					this.SendPropertyChanged("DateTime");
					this.OnDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocalCtrl", DbType="Bit")]
		public System.Nullable<bool> LocalCtrl
		{
			get
			{
				return this._LocalCtrl;
			}
			set
			{
				if ((this._LocalCtrl != value))
				{
					this.OnLocalCtrlChanging(value);
					this.SendPropertyChanging();
					this._LocalCtrl = value;
					this.SendPropertyChanged("LocalCtrl");
					this.OnLocalCtrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RemoteCtrl", DbType="Bit")]
		public System.Nullable<bool> RemoteCtrl
		{
			get
			{
				return this._RemoteCtrl;
			}
			set
			{
				if ((this._RemoteCtrl != value))
				{
					this.OnRemoteCtrlChanging(value);
					this.SendPropertyChanging();
					this._RemoteCtrl = value;
					this.SendPropertyChanged("RemoteCtrl");
					this.OnRemoteCtrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FilaSupply", DbType="Bit")]
		public System.Nullable<bool> FilaSupply
		{
			get
			{
				return this._FilaSupply;
			}
			set
			{
				if ((this._FilaSupply != value))
				{
					this.OnFilaSupplyChanging(value);
					this.SendPropertyChanging();
					this._FilaSupply = value;
					this.SendPropertyChanged("FilaSupply");
					this.OnFilaSupplyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Preheat", DbType="Bit")]
		public System.Nullable<bool> Preheat
		{
			get
			{
				return this._Preheat;
			}
			set
			{
				if ((this._Preheat != value))
				{
					this.OnPreheatChanging(value);
					this.SendPropertyChanging();
					this._Preheat = value;
					this.SendPropertyChanged("Preheat");
					this.OnPreheatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RepeatCycle", DbType="Bit")]
		public System.Nullable<bool> RepeatCycle
		{
			get
			{
				return this._RepeatCycle;
			}
			set
			{
				if ((this._RepeatCycle != value))
				{
					this.OnRepeatCycleChanging(value);
					this.SendPropertyChanging();
					this._RepeatCycle = value;
					this.SendPropertyChanged("RepeatCycle");
					this.OnRepeatCycleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Antenna", DbType="Bit")]
		public System.Nullable<bool> Antenna
		{
			get
			{
				return this._Antenna;
			}
			set
			{
				if ((this._Antenna != value))
				{
					this.OnAntennaChanging(value);
					this.SendPropertyChanging();
					this._Antenna = value;
					this.SendPropertyChanged("Antenna");
					this.OnAntennaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Load]", Storage="_Load", DbType="Bit")]
		public System.Nullable<bool> Load
		{
			get
			{
				return this._Load;
			}
			set
			{
				if ((this._Load != value))
				{
					this.OnLoadChanging(value);
					this.SendPropertyChanging();
					this._Load = value;
					this.SendPropertyChanged("Load");
					this.OnLoadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AllowOn", DbType="Bit")]
		public System.Nullable<bool> AllowOn
		{
			get
			{
				return this._AllowOn;
			}
			set
			{
				if ((this._AllowOn != value))
				{
					this.OnAllowOnChanging(value);
					this.SendPropertyChanging();
					this._AllowOn = value;
					this.SendPropertyChanged("AllowOn");
					this.OnAllowOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BroadPulse", DbType="Bit")]
		public System.Nullable<bool> BroadPulse
		{
			get
			{
				return this._BroadPulse;
			}
			set
			{
				if ((this._BroadPulse != value))
				{
					this.OnBroadPulseChanging(value);
					this.SendPropertyChanging();
					this._BroadPulse = value;
					this.SendPropertyChanged("BroadPulse");
					this.OnBroadPulseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpikePulse", DbType="Bit")]
		public System.Nullable<bool> SpikePulse
		{
			get
			{
				return this._SpikePulse;
			}
			set
			{
				if ((this._SpikePulse != value))
				{
					this.OnSpikePulseChanging(value);
					this.SendPropertyChanging();
					this._SpikePulse = value;
					this.SendPropertyChanged("SpikePulse");
					this.OnSpikePulseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Auto", DbType="Bit")]
		public System.Nullable<bool> Auto
		{
			get
			{
				return this._Auto;
			}
			set
			{
				if ((this._Auto != value))
				{
					this.OnAutoChanging(value);
					this.SendPropertyChanging();
					this._Auto = value;
					this.SendPropertyChanged("Auto");
					this.OnAutoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Manual", DbType="Bit")]
		public System.Nullable<bool> Manual
		{
			get
			{
				return this._Manual;
			}
			set
			{
				if ((this._Manual != value))
				{
					this.OnManualChanging(value);
					this.SendPropertyChanging();
					this._Manual = value;
					this.SendPropertyChanged("Manual");
					this.OnManualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HighVolon", DbType="Bit")]
		public System.Nullable<bool> HighVolon
		{
			get
			{
				return this._HighVolon;
			}
			set
			{
				if ((this._HighVolon != value))
				{
					this.OnHighVolonChanging(value);
					this.SendPropertyChanging();
					this._HighVolon = value;
					this.SendPropertyChanged("HighVolon");
					this.OnHighVolonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HighVoloff", DbType="Bit")]
		public System.Nullable<bool> HighVoloff
		{
			get
			{
				return this._HighVoloff;
			}
			set
			{
				if ((this._HighVoloff != value))
				{
					this.OnHighVoloffChanging(value);
					this.SendPropertyChanging();
					this._HighVoloff = value;
					this.SendPropertyChanged("HighVoloff");
					this.OnHighVoloffChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fault", DbType="Bit")]
		public System.Nullable<bool> Fault
		{
			get
			{
				return this._Fault;
			}
			set
			{
				if ((this._Fault != value))
				{
					this.OnFaultChanging(value);
					this.SendPropertyChanging();
					this._Fault = value;
					this.SendPropertyChanged("Fault");
					this.OnFaultChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Backup]", Storage="_Backup", DbType="Bit")]
		public System.Nullable<bool> Backup
		{
			get
			{
				return this._Backup;
			}
			set
			{
				if ((this._Backup != value))
				{
					this.OnBackupChanging(value);
					this.SendPropertyChanging();
					this._Backup = value;
					this.SendPropertyChanged("Backup");
					this.OnBackupChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PowerDataTable")]
	public partial class PowerDataTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID;
		
		private string _StationID;
		
		private System.DateTime _DateTime;
		
		private System.Nullable<decimal> _Vol5;
		
		private System.Nullable<decimal> _Vol15;
		
		private System.Nullable<decimal> _VolNeg15;
		
		private System.Nullable<decimal> _Vol28;
		
		private System.Nullable<decimal> _Vol45;
		
		private System.Nullable<decimal> _Vol510;
		
		private System.Nullable<decimal> _VolFilaInve;
		
		private System.Nullable<decimal> _VolFilament;
		
		private System.Nullable<decimal> _VolField;
		
		private System.Nullable<decimal> _VolTitPump;
		
		private System.Nullable<decimal> _VolEleBeam;
		
		private System.Nullable<decimal> _VolArtifLine;
		
		private System.Nullable<decimal> _CurCatho;
		
		private System.Nullable<decimal> _CurReversePeak;
		
		private System.Nullable<decimal> _CurFilament;
		
		private System.Nullable<decimal> _CurFocusCoil;
		
		private System.Nullable<decimal> _CurTitPump;
		
		private System.Nullable<decimal> _CurLeveling;
		
		private System.Nullable<decimal> _CurArtifLine;
		
	#region 可扩展性方法定义
	partial void OnLoaded();
	partial void OnValidate(System.Data.Linq.ChangeAction action);
	partial void OnCreated();
	partial void OnIDChanging(System.Guid value);
	partial void OnIDChanged();
	partial void OnStationIDChanging(string value);
	partial void OnStationIDChanged();
	partial void OnDateTimeChanging(System.DateTime value);
	partial void OnDateTimeChanged();
	partial void OnVol5Changing(System.Nullable<decimal> value);
	partial void OnVol5Changed();
	partial void OnVol15Changing(System.Nullable<decimal> value);
	partial void OnVol15Changed();
	partial void OnVolNeg15Changing(System.Nullable<decimal> value);
	partial void OnVolNeg15Changed();
	partial void OnVol28Changing(System.Nullable<decimal> value);
	partial void OnVol28Changed();
	partial void OnVol45Changing(System.Nullable<decimal> value);
	partial void OnVol45Changed();
	partial void OnVol510Changing(System.Nullable<decimal> value);
	partial void OnVol510Changed();
	partial void OnVolFilaInveChanging(System.Nullable<decimal> value);
	partial void OnVolFilaInveChanged();
	partial void OnVolFilamentChanging(System.Nullable<decimal> value);
	partial void OnVolFilamentChanged();
	partial void OnVolFieldChanging(System.Nullable<decimal> value);
	partial void OnVolFieldChanged();
	partial void OnVolTitPumpChanging(System.Nullable<decimal> value);
	partial void OnVolTitPumpChanged();
	partial void OnVolEleBeamChanging(System.Nullable<decimal> value);
	partial void OnVolEleBeamChanged();
	partial void OnVolArtifLineChanging(System.Nullable<decimal> value);
	partial void OnVolArtifLineChanged();
	partial void OnCurCathoChanging(System.Nullable<decimal> value);
	partial void OnCurCathoChanged();
	partial void OnCurReversePeakChanging(System.Nullable<decimal> value);
	partial void OnCurReversePeakChanged();
	partial void OnCurFilamentChanging(System.Nullable<decimal> value);
	partial void OnCurFilamentChanged();
	partial void OnCurFocusCoilChanging(System.Nullable<decimal> value);
	partial void OnCurFocusCoilChanged();
	partial void OnCurTitPumpChanging(System.Nullable<decimal> value);
	partial void OnCurTitPumpChanged();
	partial void OnCurLevelingChanging(System.Nullable<decimal> value);
	partial void OnCurLevelingChanged();
	partial void OnCurArtifLineChanging(System.Nullable<decimal> value);
	partial void OnCurArtifLineChanged();
	#endregion
		
		public PowerDataTable()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StationID", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string StationID
		{
			get
			{
				return this._StationID;
			}
			set
			{
				if ((this._StationID != value))
				{
					this.OnStationIDChanging(value);
					this.SendPropertyChanging();
					this._StationID = value;
					this.SendPropertyChanged("StationID");
					this.OnStationIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTime", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime DateTime
		{
			get
			{
				return this._DateTime;
			}
			set
			{
				if ((this._DateTime != value))
				{
					this.OnDateTimeChanging(value);
					this.SendPropertyChanging();
					this._DateTime = value;
					this.SendPropertyChanged("DateTime");
					this.OnDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vol5", DbType="Decimal(6,2)")]
		public System.Nullable<decimal> Vol5
		{
			get
			{
				return this._Vol5;
			}
			set
			{
				if ((this._Vol5 != value))
				{
					this.OnVol5Changing(value);
					this.SendPropertyChanging();
					this._Vol5 = value;
					this.SendPropertyChanged("Vol5");
					this.OnVol5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vol15", DbType="Decimal(6,2)")]
		public System.Nullable<decimal> Vol15
		{
			get
			{
				return this._Vol15;
			}
			set
			{
				if ((this._Vol15 != value))
				{
					this.OnVol15Changing(value);
					this.SendPropertyChanging();
					this._Vol15 = value;
					this.SendPropertyChanged("Vol15");
					this.OnVol15Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VolNeg15", DbType="Decimal(6,2)")]
		public System.Nullable<decimal> VolNeg15
		{
			get
			{
				return this._VolNeg15;
			}
			set
			{
				if ((this._VolNeg15 != value))
				{
					this.OnVolNeg15Changing(value);
					this.SendPropertyChanging();
					this._VolNeg15 = value;
					this.SendPropertyChanged("VolNeg15");
					this.OnVolNeg15Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vol28", DbType="Decimal(6,2)")]
		public System.Nullable<decimal> Vol28
		{
			get
			{
				return this._Vol28;
			}
			set
			{
				if ((this._Vol28 != value))
				{
					this.OnVol28Changing(value);
					this.SendPropertyChanging();
					this._Vol28 = value;
					this.SendPropertyChanged("Vol28");
					this.OnVol28Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vol45", DbType="Decimal(6,2)")]
		public System.Nullable<decimal> Vol45
		{
			get
			{
				return this._Vol45;
			}
			set
			{
				if ((this._Vol45 != value))
				{
					this.OnVol45Changing(value);
					this.SendPropertyChanging();
					this._Vol45 = value;
					this.SendPropertyChanged("Vol45");
					this.OnVol45Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vol510", DbType="Decimal(6,2)")]
		public System.Nullable<decimal> Vol510
		{
			get
			{
				return this._Vol510;
			}
			set
			{
				if ((this._Vol510 != value))
				{
					this.OnVol510Changing(value);
					this.SendPropertyChanging();
					this._Vol510 = value;
					this.SendPropertyChanged("Vol510");
					this.OnVol510Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VolFilaInve", DbType="Decimal(6,2)")]
		public System.Nullable<decimal> VolFilaInve
		{
			get
			{
				return this._VolFilaInve;
			}
			set
			{
				if ((this._VolFilaInve != value))
				{
					this.OnVolFilaInveChanging(value);
					this.SendPropertyChanging();
					this._VolFilaInve = value;
					this.SendPropertyChanged("VolFilaInve");
					this.OnVolFilaInveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VolFilament", DbType="Decimal(6,2)")]
		public System.Nullable<decimal> VolFilament
		{
			get
			{
				return this._VolFilament;
			}
			set
			{
				if ((this._VolFilament != value))
				{
					this.OnVolFilamentChanging(value);
					this.SendPropertyChanging();
					this._VolFilament = value;
					this.SendPropertyChanged("VolFilament");
					this.OnVolFilamentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VolField", DbType="Decimal(6,2)")]
		public System.Nullable<decimal> VolField
		{
			get
			{
				return this._VolField;
			}
			set
			{
				if ((this._VolField != value))
				{
					this.OnVolFieldChanging(value);
					this.SendPropertyChanging();
					this._VolField = value;
					this.SendPropertyChanged("VolField");
					this.OnVolFieldChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VolTitPump", DbType="Decimal(6,2)")]
		public System.Nullable<decimal> VolTitPump
		{
			get
			{
				return this._VolTitPump;
			}
			set
			{
				if ((this._VolTitPump != value))
				{
					this.OnVolTitPumpChanging(value);
					this.SendPropertyChanging();
					this._VolTitPump = value;
					this.SendPropertyChanged("VolTitPump");
					this.OnVolTitPumpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VolEleBeam", DbType="Decimal(6,2)")]
		public System.Nullable<decimal> VolEleBeam
		{
			get
			{
				return this._VolEleBeam;
			}
			set
			{
				if ((this._VolEleBeam != value))
				{
					this.OnVolEleBeamChanging(value);
					this.SendPropertyChanging();
					this._VolEleBeam = value;
					this.SendPropertyChanged("VolEleBeam");
					this.OnVolEleBeamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VolArtifLine", DbType="Decimal(6,2)")]
		public System.Nullable<decimal> VolArtifLine
		{
			get
			{
				return this._VolArtifLine;
			}
			set
			{
				if ((this._VolArtifLine != value))
				{
					this.OnVolArtifLineChanging(value);
					this.SendPropertyChanging();
					this._VolArtifLine = value;
					this.SendPropertyChanged("VolArtifLine");
					this.OnVolArtifLineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurCatho", DbType="Decimal(6,2)")]
		public System.Nullable<decimal> CurCatho
		{
			get
			{
				return this._CurCatho;
			}
			set
			{
				if ((this._CurCatho != value))
				{
					this.OnCurCathoChanging(value);
					this.SendPropertyChanging();
					this._CurCatho = value;
					this.SendPropertyChanged("CurCatho");
					this.OnCurCathoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurReversePeak", DbType="Decimal(6,2)")]
		public System.Nullable<decimal> CurReversePeak
		{
			get
			{
				return this._CurReversePeak;
			}
			set
			{
				if ((this._CurReversePeak != value))
				{
					this.OnCurReversePeakChanging(value);
					this.SendPropertyChanging();
					this._CurReversePeak = value;
					this.SendPropertyChanged("CurReversePeak");
					this.OnCurReversePeakChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurFilament", DbType="Decimal(6,2)")]
		public System.Nullable<decimal> CurFilament
		{
			get
			{
				return this._CurFilament;
			}
			set
			{
				if ((this._CurFilament != value))
				{
					this.OnCurFilamentChanging(value);
					this.SendPropertyChanging();
					this._CurFilament = value;
					this.SendPropertyChanged("CurFilament");
					this.OnCurFilamentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurFocusCoil", DbType="Decimal(6,2)")]
		public System.Nullable<decimal> CurFocusCoil
		{
			get
			{
				return this._CurFocusCoil;
			}
			set
			{
				if ((this._CurFocusCoil != value))
				{
					this.OnCurFocusCoilChanging(value);
					this.SendPropertyChanging();
					this._CurFocusCoil = value;
					this.SendPropertyChanged("CurFocusCoil");
					this.OnCurFocusCoilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurTitPump", DbType="Decimal(6,2)")]
		public System.Nullable<decimal> CurTitPump
		{
			get
			{
				return this._CurTitPump;
			}
			set
			{
				if ((this._CurTitPump != value))
				{
					this.OnCurTitPumpChanging(value);
					this.SendPropertyChanging();
					this._CurTitPump = value;
					this.SendPropertyChanged("CurTitPump");
					this.OnCurTitPumpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurLeveling", DbType="Decimal(6,2)")]
		public System.Nullable<decimal> CurLeveling
		{
			get
			{
				return this._CurLeveling;
			}
			set
			{
				if ((this._CurLeveling != value))
				{
					this.OnCurLevelingChanging(value);
					this.SendPropertyChanging();
					this._CurLeveling = value;
					this.SendPropertyChanged("CurLeveling");
					this.OnCurLevelingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurArtifLine", DbType="Decimal(6,2)")]
		public System.Nullable<decimal> CurArtifLine
		{
			get
			{
				return this._CurArtifLine;
			}
			set
			{
				if ((this._CurArtifLine != value))
				{
					this.OnCurArtifLineChanging(value);
					this.SendPropertyChanging();
					this._CurArtifLine = value;
					this.SendPropertyChanged("CurArtifLine");
					this.OnCurArtifLineChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StationParaTable")]
	public partial class StationParaTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID;
		
		private string _StationID;
		
		private string _StationName;
		
		private string _Slong;
		
		private string _Slat;
		
		private string _Address;
		
	#region 可扩展性方法定义
	partial void OnLoaded();
	partial void OnValidate(System.Data.Linq.ChangeAction action);
	partial void OnCreated();
	partial void OnIDChanging(System.Guid value);
	partial void OnIDChanged();
	partial void OnStationIDChanging(string value);
	partial void OnStationIDChanged();
	partial void OnStationNameChanging(string value);
	partial void OnStationNameChanged();
	partial void OnSlongChanging(string value);
	partial void OnSlongChanged();
	partial void OnSlatChanging(string value);
	partial void OnSlatChanged();
	partial void OnAddressChanging(string value);
	partial void OnAddressChanged();
	#endregion
		
		public StationParaTable()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StationID", DbType="NVarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string StationID
		{
			get
			{
				return this._StationID;
			}
			set
			{
				if ((this._StationID != value))
				{
					this.OnStationIDChanging(value);
					this.SendPropertyChanging();
					this._StationID = value;
					this.SendPropertyChanged("StationID");
					this.OnStationIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StationName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string StationName
		{
			get
			{
				return this._StationName;
			}
			set
			{
				if ((this._StationName != value))
				{
					this.OnStationNameChanging(value);
					this.SendPropertyChanging();
					this._StationName = value;
					this.SendPropertyChanged("StationName");
					this.OnStationNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Slong", DbType="NVarChar(7)")]
		public string Slong
		{
			get
			{
				return this._Slong;
			}
			set
			{
				if ((this._Slong != value))
				{
					this.OnSlongChanging(value);
					this.SendPropertyChanging();
					this._Slong = value;
					this.SendPropertyChanged("Slong");
					this.OnSlongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Slat", DbType="NVarChar(6)")]
		public string Slat
		{
			get
			{
				return this._Slat;
			}
			set
			{
				if ((this._Slat != value))
				{
					this.OnSlatChanging(value);
					this.SendPropertyChanging();
					this._Slat = value;
					this.SendPropertyChanged("Slat");
					this.OnSlatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(255)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
