//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/t4models).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;

using LinqToDB;
using LinqToDB.DataProvider;
using LinqToDB.Mapping;

namespace LocalRadarDataModels
{
    /// <summary>
    /// Database       : LocalRadarData
    /// Data Source    : LocalRadarData
    /// Server Version : 3.8.8.3
    /// </summary>
    public partial class LocalRadarDataDb : LinqToDB.Data.DataConnection
    {
        public ITable<AlarmStatusModels> AlarmStatus { get { return this.GetTable<AlarmStatusModels>(); } }
        public ITable<ControlStatusModels> ControlStatus { get { return this.GetTable<ControlStatusModels>(); } }
        public ITable<PowerDataModels> PowerData { get { return this.GetTable<PowerDataModels>(); } }

        public LocalRadarDataDb()
        {
            InitDataContext();
        }
        
        public LocalRadarDataDb(IDataProvider dataProvider, string configuration)
            : base(dataProvider, configuration)
        {
            InitDataContext();
        }

        public LocalRadarDataDb(string configuration)
            : base(configuration)
        {
            InitDataContext();
        }

        partial void InitDataContext();
    }

    [Table("AlarmStatus")]
    public partial class AlarmStatusModels
    {
        [Column(), NotNull]
        public string StationID { get; set; } // nvarchar(5)
        [Column(), NotNull]
        public DateTime DateTime { get; set; } // datetime
        [Column(), Nullable]
        public bool? PowerGridUnderVolOnce { get; set; } // bit
        [Column(), Nullable]
        public bool? PowerGridUnderVolQuintic { get; set; } // bit
        [Column(), Nullable]
        public bool? LowPowerFailureOnce { get; set; } // bit
        [Column(), Nullable]
        public bool? LowPowerFailureQuintic { get; set; } // bit
        [Column(), Nullable]
        public bool? FilaVolFailureOnce { get; set; } // bit
        [Column(), Nullable]
        public bool? FilaVolFailureQuintic { get; set; } // bit
        [Column(), Nullable]
        public bool? TitPumpFailureOnce { get; set; } // bit
        [Column(), Nullable]
        public bool? TitPumpFailureQuintic { get; set; } // bit
        [Column(), Nullable]
        public bool? FocusCoilVolFailureOnce { get; set; } // bit
        [Column(), Nullable]
        public bool? FocusCoilVolFailureQuintic { get; set; } // bit
        [Column(), Nullable]
        public bool? TransmitOverVolOnce { get; set; } // bit
        [Column(), Nullable]
        public bool? TransmitOverVolQuintic { get; set; } // bit
        [Column(), Nullable]
        public bool? TransmitOverCurOnce { get; set; } // bit
        [Column(), Nullable]
        public bool? TransmitOverCurQuintic { get; set; } // bit
        [Column(), Nullable]
        public bool? FocusCoilCurFailureOnce { get; set; } // bit
        [Column(), Nullable]
        public bool? FocusCoilCurFailureQuintic { get; set; } // bit
        [Column(), Nullable]
        public bool? FocusCoilAirFlowFailureOnce { get; set; } // bit
        [Column(), Nullable]
        public bool? FocusCoilAirFlowFailureQuintic { get; set; } // bit
        [Column(), Nullable]
        public bool? TriggerFailureOnce { get; set; } // bit
        [Column(), Nullable]
        public bool? TriggerFailureQuintic { get; set; } // bit
        [Column(), Nullable]
        public bool? ChargingFeedbackFlowRectifierUnderVolOnce { get; set; } // bit
        [Column(), Nullable]
        public bool? ChargingFeedbackFlowRectifierUnderVolQuintic { get; set; } // bit
        [Column(), Nullable]
        public bool? ChargingFailureOnce { get; set; } // bit
        [Column(), Nullable]
        public bool? ChargingFailureQuintic { get; set; } // bit
        [Column(), Nullable]
        public bool? ModulatorOverOnce { get; set; } // bit
        [Column(), Nullable]
        public bool? ModulatorOverQuintic { get; set; } // bit
        [Column(), Nullable]
        public bool? ModulatorNegPeakOverOnce { get; set; } // bit
        [Column(), Nullable]
        public bool? ModulatorNegPeakOverQuintic { get; set; } // bit
        [Column(), Nullable]
        public bool? ModulatorSwitchFailureOnce { get; set; } // bit
        [Column(), Nullable]
        public bool? ModulatorSwitchFailureQuintic { get; set; } // bit
        [Column(), Nullable]
        public bool? KlystronOverCurOnce { get; set; } // bit
        [Column(), Nullable]
        public bool? KlystronOverCurQuintic { get; set; } // bit
        [Column(), Nullable]
        public bool? KlystronFilaFailureOnce { get; set; } // bit
        [Column(), Nullable]
        public bool? KlystronFilaFailureQuintic { get; set; } // bit
        [Column(), Nullable]
        public bool? KlystronTitPumpFailureOnce { get; set; } // bit
        [Column(), Nullable]
        public bool? KlystronTitPumpFailureQuintic { get; set; } // bit
        [Column(), Nullable]
        public bool? KlystronAirTempAlarmOnce { get; set; } // bit
        [Column(), Nullable]
        public bool? KlystronAirTempAlarmQuintic { get; set; } // bit
        [Column(), Nullable]
        public bool? KlystronAirFlowAlarmOnce { get; set; } // bit
        [Column(), Nullable]
        public bool? KlystronAirFlowAlarmQuintic { get; set; } // bit
        [Column(), Nullable]
        public bool? WaveGuidPressAlarmOnce { get; set; } // bit
        [Column(), Nullable]
        public bool? WaveGuidPressAlarmQuintic { get; set; } // bit
        [Column(), Nullable]
        public bool? WaveGuidArcAlarmOnce { get; set; } // bit
        [Column(), Nullable]
        public bool? WaveGuidArcAlarmQuintic { get; set; } // bit
        [Column(), Nullable]
        public bool? TankLevelAlarmOnce { get; set; } // bit
        [Column(), Nullable]
        public bool? TankLevelAlarmQuintic { get; set; } // bit
        [Column(), Nullable]
        public bool? TankTempAlarmOnce { get; set; } // bit
        [Column(), Nullable]
        public bool? TankTempAlarmQuintic { get; set; } // bit
        [Column(), Nullable]
        public bool? AntennaWaveGuidChain { get; set; } // bit
        [Column(), Nullable]
        public bool? AntennaCirculatorOverHeat { get; set; } // bit
        [Column(), Nullable]
        public bool? RackDoorChainOnce { get; set; } // bit
        [Column(), Nullable]
        public bool? RackDoorChainQuintic { get; set; } // bit
        [Column(), Nullable]
        public bool? RackAirTempAlarmOnce { get; set; } // bit
        [Column(), Nullable]
        public bool? RackAirTempAlarmQuintic { get; set; } // bit
        [Column(), Nullable]
        public bool? RackAirFlowAlarmOnce { get; set; } // bit
        [Column(), Nullable]
        public bool? RackAirFlowAlarmQuintic { get; set; } // bit
        [Column(), Nullable]
        public bool? DutyCycleOverOnce { get; set; } // bit
        [Column(), Nullable]
        public bool? DutyCycleOverQuintic { get; set; } // bit
        [Column(), Nullable]
        public bool? WaveGuidPressHumidityReq { get; set; } // bit
        [Column(), Nullable]
        public bool? ModulatorSwitchReq { get; set; } // bit
        [Column(), Nullable]
        public bool? AfterChargingFair { get; set; } // bit
        [Column("510VFailureOnce"), Nullable]
        public bool? _510VFailureOnce { get; set; } // bit
        [Column("510VFailureQuintic"), Nullable]
        public bool? _510VFailureQuintic { get; set; } // bit
        [Column(), Nullable]
        public bool? BackupOnce { get; set; } // bit
        [Column(), Nullable]
        public bool? BackupQuintic { get; set; } // bit
    }

    [Table("ControlStatus")]
    public partial class ControlStatusModels
    {
        [Column, NotNull]
        public string StationID { get; set; } // nvarchar(5)
        [Column, NotNull]
        public DateTime DateTime { get; set; } // datetime
        [Column, Nullable]
        public bool? LocalCtrl { get; set; } // bit
        [Column, Nullable]
        public bool? RemoteCtrl { get; set; } // bit
        [Column, Nullable]
        public bool? FilaSupply { get; set; } // bit
        [Column, Nullable]
        public bool? Preheat { get; set; } // bit
        [Column, Nullable]
        public bool? RepeatCycle { get; set; } // bit
        [Column, Nullable]
        public bool? Antenna { get; set; } // bit
        [Column, Nullable]
        public bool? Load { get; set; } // bit
        [Column, Nullable]
        public bool? AllowOn { get; set; } // bit
        [Column, Nullable]
        public bool? BroadPulse { get; set; } // bit
        [Column, Nullable]
        public bool? SpikePulse { get; set; } // bit
        [Column, Nullable]
        public bool? Auto { get; set; } // bit
        [Column, Nullable]
        public bool? Manual { get; set; } // bit
        [Column, Nullable]
        public bool? HighVolon { get; set; } // bit
        [Column, Nullable]
        public bool? HighVoloff { get; set; } // bit
        [Column, Nullable]
        public bool? Fault { get; set; } // bit
        [Column, Nullable]
        public bool? Backup { get; set; } // bit
    }

    [Table("PowerData")]
    public partial class PowerDataModels
    {
        [Column, NotNull]
        public string StationID { get; set; } // nvarchar(5)
        [Column, NotNull]
        public DateTime DateTime { get; set; } // datetime
        [Column, Nullable]
        public decimal? Vol5 { get; set; } // decimal
        [Column, Nullable]
        public decimal? Vol15 { get; set; } // decimal
        [Column, Nullable]
        public decimal? VolNeg15 { get; set; } // decimal
        [Column, Nullable]
        public decimal? Vol28 { get; set; } // decimal
        [Column, Nullable]
        public decimal? Vol45 { get; set; } // decimal
        [Column, Nullable]
        public decimal? Vol510 { get; set; } // decimal
        [Column, Nullable]
        public decimal? VolFilaInve { get; set; } // decimal
        [Column, Nullable]
        public decimal? VolFilament { get; set; } // decimal
        [Column, Nullable]
        public decimal? VolField { get; set; } // decimal
        [Column, Nullable]
        public decimal? VolTitPump { get; set; } // decimal
        [Column, Nullable]
        public decimal? VolEleBeam { get; set; } // decimal
        [Column, Nullable]
        public decimal? VolArtifLine { get; set; } // decimal
        [Column, Nullable]
        public decimal? CurCatho { get; set; } // decimal
        [Column, Nullable]
        public decimal? CurReversePeak { get; set; } // decimal
        [Column, Nullable]
        public decimal? CurFilament { get; set; } // decimal
        [Column, Nullable]
        public decimal? CurFocusCoil { get; set; } // decimal
        [Column, Nullable]
        public decimal? CurTitPump { get; set; } // decimal
        [Column, Nullable]
        public decimal? CurLeveling { get; set; } // decimal
        [Column, Nullable]
        public decimal? CurArtifLine { get; set; } // decimal
    }
}
